stages:
  - build
  - deploy

.build: &build
  image: node:13
  stage: build
  script:
    - yarn audit
    - yarn install
    - yarn build
  artifacts:
    expire_in: 15 minutes
    paths:
      - build

build:latest:
  <<: *build

.deploy: &deploy
  image: dockito/lftp-client
  stage: deploy

deploy:dev:
  <<: *deploy
  script:
    - lftp -e 'mirror -R build /safesafe-dev; bye' -u $STAGE_FTP_USER,$STAGE_FTP_PASS $STAGE__FTP_HOST
  when: manual

deploy:stage:
  <<: *deploy
  script:
    - lftp -e 'mirror -R build /safesafe; ; bye' -u $STAGE_FTP_USER,$STAGE_FTP_PASS $STAGE__FTP_HOST
  when: manual
