stages:
  - build
  - deploy

.build: &build
  image: node:13
  stage: build
  script:
    - yarn install
    - yarn build
  artifacts:
    expire_in: 15 minutes
    paths:
      - build

build:latest:
  <<: *build
  except:
    - tags

build:prod:
  <<: *build
  only:
    - /^\d\.\d\.\d*-*\d*$/
  except:
    - branches
    - triggers

.deploy: &deploy
  image: casao/lftp-ssh
  stage: deploy

deploy:stage:
  <<: *deploy
  script:
      - lftp -e 'cd /test; mput build/* ; bye' -u $STAGE_FTP_USER,$STAGE_FTP_PASS $STAGE__FTP_HOST
  only:
    - master
