---

name: Manaul trigger with locales PR
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to make PR on'
        required: true

jobs:

  Setup:
    runs-on: ubuntu-latest
    outputs:
      COMMIT_TO: ${{ env.COMMIT_TO }}
      SOURCE_BRANCH: ${{ env.SOURCE_BRANCH }}
      ENVIRONMENT: ${{ env.ENVIRONMENT }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check if its DEV repo
        if: github.repository_owner != 'ProteGO-Safe'
        run: |
          echo "ENVIRONMENT=DEV" >> $GITHUB_ENV

      - name: Set ENV's
        run: |
            echo "COMMIT_TO=${{ github.event.inputs.branch }}" >> $GITHUB_ENV
            echo "SOURCE_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
        shell: bash
      
  POE_PR:
    runs-on: ubuntu-latest
    needs: [Setup]
    if: needs.Setup.outputs.ENVIRONMENT == 'DEV'
    env:
      COMMIT_TO: ${{ needs.Setup.outputs.COMMIT_TO }}
      SOURCE_BRANCH: ${{ needs.Setup.outputs.SOURCE_BRANCH }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ env.SOURCE_BRANCH }}

      - name: Download REMOTE LOCALES from POEditor
        run: |
          for l in $(find locales -type f -maxdepth 1 -name "*.json" -exec basename {} .json ';')
          do
            echo "Processing $l"
          	sh  locales/scripts/export.sh  -i ${{ secrets.POEDITOR_ID }} -t ${{ secrets.POEDITOR_TOKEN }} -l $l
          done
        shell: bash

      - name: Get current date
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d_%H:%M')" >> $GITHUB_ENV
      
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update Locales
          base: ${{ env.COMMIT_TO }}
          branch: ${{ env.SOURCE_BRANCH }}
          draft: true
          title: '[LOCALES] Update to ${{ env.CURRENT_DATE }}'
          body: |
            Update locales
          labels: |
            locales
            automated pr

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
